### ISSUE TITLE
Implementing Husky for Pre-Push Hooks to Prevent Production Bugs

### ISSUE THREAD

**Issue by BirushaNdegeya** [kaliacad/wikidataqueriIA#79]
To ensure code quality and prevent potential production bugs, we will integrate Husky into our workflow. This tool will allow us to set up pre-push hooks that automatically run specified checks (e.g., linting, testing) before any code is pushed to the repository. By doing so, we can catch errors early and maintain a stable production environment. This initiative will help safeguard our codebase and streamline our development process.

![lint-error-prevent-by-husky](https://github.com/user-attachments/assets/0654cd13-8c88-49f0-a615-a9cd5dd62d2a)

**Comment by bhima2001** [comment]
Hey, Can I work on this issue?

**Comment by Bam92** [comment]
Hey!

I've assigned it to you. Thank you for your help.

**Comment by bhima2001** [comment]
https://github.com/kaliacad/wikidataqueriIA/pull/81 --> This is the PR. Please let me know if any changes are required
